name: CI CD TEST

on: 
  push:
    branches: [master]
  pull_request:

jobs:
  build-and-push:
    name: BUILD and PUSH to Docker HUB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker Build
        id: buildx
        uses: docker-setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./cmd
          tags: |
            ${{ secrets.DH_USERNAME }}/hello-world-yt:latest
          push: ${{ github.ref = 'refs/heads/master' }}
       
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

